Fix getting started example: pass float instead of int parameter
Before:
```
flytekit.core.type_engine.TypeTransformerFailedError: Type of Val '1' is not an instance of <class 'float'>
```

After:
Can run main successfully

Signed-off-by: Robert Fink <rf@robertfink.de>