Fix flyte-core rendering when flyteagent enabled
 - Flyte agent now tries to render a specific set of podLabels, so
   assumes that there is an empty `podLabels: {}` set. This change to
   values.yaml for flyte-core ensures empty values are there.

 - Fixes:

   Error: template: flyte-core/charts/flyteagent/templates/agent/deployment.yaml:17:17: executing "flyte-core/charts/flyteagent/templates/agent/deployment.yaml" at <include "flyteagent.podLabels" .>: error calling include: template: flyte-core/templates/_helpers.tpl:122:16: executing "flyteagent.podLabels" at <.Values.flyteagent.podLabels>: nil pointer evaluating interface {}.podLabels

Signed-off-by: ddl-ebrown <ethan.brown@dominodatalab.com>